apiVersion: v1
kind: Service
metadata:
  name: kubia-service
  labels:
    service: kubia-service
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: kubia