apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia-rs
spec:
  replicas: 3
  selector:
     matchLabels:
       app: kubia  
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: navkkrnair/kubia:rs
        imagePullPolicy: Always
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          httpGet:
            path: /actuator/health
            port: 8080
                        
        ports:
        - containerPort: 8080