apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc
  labels:
    type: rc
    description: rc for kubia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: replaceme
        image: replaceme
        ports:
        - containerPort: 8080