apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
   - image: navkkrnair/kubia:unhealthy
     name: kubia-unhealthy
     imagePullPolicy: Always
     livenessProbe:
       httpGet:
         path: /
         port: 8080
       #initialDelaySeconds: 20  
     ports:
      - containerPort: 8080
        protocol: TCP  
  