apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia-rc
        image: navkkrnair/kubia:rc
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080            
        ports:
        - containerPort: 8080