apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness-with-actuator
spec:
  containers:
   - image: navkkrnair/kubia:actuator
     name: kubia-unhealthy
     imagePullPolicy: Always
     livenessProbe:
       httpGet:
         path: /actuator/health
         port: 8080
       initialDelaySeconds: 30  
     ports:
      - containerPort: 8080
        protocol: TCP  
  