apiVersion: v1
kind: Service
metadata:
  name: kubia-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: http2
      port: 443
      targetPort: http2
  selector:
   app: kubia
     
  