kind: ReplicationController
apiVersion: v1
metadata:
  name: kubia-v1-rc
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
         app: kubia
    spec:
       containers:
         - name: kubia-v1-container
           image: navkkrnair/kubia:v1
           imagePullPolicy: Always
           ports:
             - name: http 
               containerPort: 8080
               protocol: TCP
               
---
apiVersion: v1
kind: Service
metadata:
  name: kubia-service
  labels:
    service: kubia-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: kubia