apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia-deployment
  labels:
    service: kubia-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia-container      
        image: navkkrnair/kubia:v1
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          exec:
            command:
             - ls
             - /var/ready  
          initialDelaySeconds: 60
          
---
apiVersion: v1
kind: Service
metadata:
  name: kubia-service
  labels:
    service: kubia-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: kubia          