apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
spec:
  containers:
   - image: navkkrnair/kubia:1.0
     name: kubia
     imagePullPolicy: Always
     ports:
      - containerPort: 8080
        protocol: TCP  
  