apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:
    app: kubia
    rel: stable
    env: prod
spec:
  containers:
   - image: navkkrnair/kubia:1.0
     name: kubia
     ports:
      - containerPort: 8080
        protocol: TCP  
  